// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_blackjack/test/modules/game/domain/usecases/draw_cards.usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_blackjack/modules/game/domain/entities/entities.dart'
    as _i4;
import 'package:flutter_blackjack/modules/game/domain/repositories/card.repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRepository extends _i1.Mock implements _i2.CardRepository {
  @override
  _i3.Future<List<_i4.CardEntity>> drawCards({
    required String? deckId,
    required int? count,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #drawCards,
          [],
          {
            #deckId: deckId,
            #count: count,
          },
        ),
        returnValue: _i3.Future<List<_i4.CardEntity>>.value(<_i4.CardEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CardEntity>>.value(<_i4.CardEntity>[]),
      ) as _i3.Future<List<_i4.CardEntity>>);
}
